In [1]:
import pandas as pd

In [2]:
day_1 = pd.read_csv("dataset/02-14-2018.csv")
day_2 = pd.read_csv("dataset/02-15-2018.csv")
day_3 = pd.read_csv("dataset/02-16-2018.csv")
day_4 = pd.read_csv("dataset/02-20-2018.csv")
day_5 = pd.read_csv("dataset/02-21-2018.csv")
day_6 = pd.read_csv("dataset/02-22-2018.csv")
day_7 = pd.read_csv("dataset/02-23-2018.csv")
day_8 = pd.read_csv("dataset/02-28-2018.csv")
day_9 = pd.read_csv("dataset/03-01-2018.csv") 
day_10 = pd.read_csv("dataset/03-02-2018.csv")

/var/folders/32/k38b9t214jgb15jl2spbm24w0000gn/T/ipykernel_14651/4275634988.py:3: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  day_3 = pd.read_csv("dataset/02-16-2018.csv")
/var/folders/32/k38b9t214jgb15jl2spbm24w0000gn/T/ipykernel_14651/4275634988.py:8: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  day_8 = pd.read_csv("dataset/02-28-2018.csv")
/var/folders/32/k38b9t214jgb15jl2spbm24w0000gn/T/ipykernel_14651/4275634988.py:9: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  day_9 = pd.read_csv("dataset/03-01-2018.csv")

In [ ]:
### 1- Concatenating the datasets

In [8]:
dataset_1 = pd.concat([day_1, day_3 , day_5 , day_9, day_10], axis=0, ignore_index=True)

In [10]:
dataset_1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4525420,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4525421,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4525422,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4525423,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4525424,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [11]:
dataset_1["Label"].unique()

array(['Benign', 'FTP-BruteForce', 'SSH-Bruteforce',
       'DoS attacks-SlowHTTPTest', 'DoS attacks-Hulk', 'Label',
       'DDOS attack-LOIC-UDP', 'DDOS attack-HOIC', 'Infilteration', 'Bot'],
      dtype=object)

In [ ]:
##2- Removing row with erroneous 'Label' label

In [ ]:
dataset_1.drop(dataset_1.loc[dataset_1["Label"] == "Label"].index, inplace=True)

In [21]:
dataset_1["Label"].unique()

array(['Benign', 'FTP-BruteForce', 'SSH-Bruteforce',
       'DoS attacks-SlowHTTPTest', 'DoS attacks-Hulk',
       'DDOS attack-LOIC-UDP', 'DDOS attack-HOIC', 'Infilteration', 'Bot'],
      dtype=object)

In [22]:
print(dataset_1["Label"].value_counts()[['Benign']].sum())
print(dataset_1["Label"].value_counts()[['FTP-BruteForce']].sum())
print(dataset_1["Label"].value_counts()[['SSH-Bruteforce']].sum())
print(dataset_1["Label"].value_counts()[['DoS attacks-SlowHTTPTest']].sum())
print(dataset_1["Label"].value_counts()[['DoS attacks-Hulk']].sum())
print(dataset_1["Label"].value_counts()[['DDOS attack-LOIC-UDP']].sum())
print(dataset_1["Label"].value_counts()[['DDOS attack-HOIC']].sum())
print(dataset_1["Label"].value_counts()[['Infilteration']].sum())
print(dataset_1["Label"].value_counts()[['Bot']].sum())

2475652
193360
187589
139890
461912
1730
686012
93063
286191

In [23]:
##3- Creating "Malicious" label to all other labels except 'Benign'

In [26]:
dataset_1.replace(to_replace=[ 'FTP-BruteForce', 'SSH-Bruteforce',
       'DoS attacks-SlowHTTPTest', 'DoS attacks-Hulk',
       'DDOS attack-LOIC-UDP', 'DDOS attack-HOIC', 'Infilteration', 'Bot'
], value="Malicious", inplace=True)

In [27]:
dataset_1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)